### ISSUE TITLE
Why appending function arguments?

### ISSUE THREAD

**Issue by jfsalzmann** [George-lewis/superpipe#1]
Hi there,
I have a question out of interest as I see this is a pattern in most Python implementations of this type. I have an R background where in the famous magrittr pipe, the piped argument is inserted at first position. I am curious to understand the reasoning behind deciding to make it the last argument, as it seems to me when I adjust your code accordingly, I can make the R-ish way work too.
Thanks, Joff

**Comment by George-lewis** [comment]
Hi, Joff

Thanks for your message.

For some reason GitHub didn't notify me about it, or I otherwise missed it somehow until now

In a lot of Python's builtin functions, such as `map`, the lambda comes first and the iterable second, e.g. `map(lambda x: x + 1, [1, 2, 3])`, which using superpipe would look like `[1, 2, 3] >> map(lambda x: x + 1)`. If superpipe instead inserted to the front, this would not work. At some point the library supported both `>>` and `<<` operators but I deemed it to be too complex to maintain and instead decided `x >> f(_, ...)` would be good enough for the times it is needed.

I see that you have forked the project, that's very cool. What does `joffpype` do?

Regards
